// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class ClientContextDb : DataConnection
	{
		public ClientContextDb()
		{
			InitSchemas();
			InitDataContext();
		}

		public ClientContextDb(string configuration)
			: base(configuration)
		{
			InitSchemas();
			InitDataContext();
		}

		public ClientContextDb(DataOptions<ClientContextDb> options)
			: base(options.Options)
		{
			InitSchemas();
			InitDataContext();
		}

		partial void InitDataContext();

		#region Schemas
		public void InitSchemas()
		{
			Clients = new ClientsSchema.DataContext(this);
		}

		public ClientsSchema.DataContext Clients { get; set; } = null!;
		#endregion
	}
}
